### PR TITLE
fix: documentation link typos

### PR DESCRIPTION
**Pull request by francoabaroa**
Most of the links in the documentation are broken. This is a fix for them.

### CODE REVIEW

**Comment by ncitron** [comment]
Good catch! For the main binary, it's now located in `bin/magi.rs`. Can you update it to reflect that as well?

**Comment by francoabaroa** [comment]
Of course!

**Comment by francoabaroa** [comment]
All set

**Review by ncitron — APPROVED** [review]
LGTM! Thanks for the contribution!

**Pull request merged**
